inherit_from: configs/ScanNet/scannet.yaml
data:
  input_path: /home/ubuntu/xth/VGGT-SLAM-main/datasets/Scannet/scene0207_00
  output_path: output/ScanNet/scene0207
  scene_name: scene0207_00

cam: 
  fx: 575.547668
  fy: 577.459778
  cx: 323.171967
  cy: 236.417465