inherit_from: configs/Replica/replica.yaml
data:
  scene_name: office2
  input_path: /home/ubuntu/data01/xth/Gaussian-SLAM-main/data/Replica-SLAM/snapshots/Replica/office2/
  output_path: output/Replica/office2/
